### ISSUE TITLE
Game keeps crashing when attempting to open Atlas.

### ISSUE THREAD

**Issue by RokLinen** [MehVahdJukaar/mapatlases-neoforge#107]
Hello, I'm a noob when it comes to issue solving. This is my first time posting relating to a issue I'm having with a mod. I can't open the Atlas book because it crashes. I've had a similair issue with another mod that had some extra GUI options with books and symbols. Anyway here's the error log it gave me:

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-03-01 23:43:13
Description: Ticking screen

java.lang.IllegalStateException: [fabric-screen-api-v1] The current screen (pepjebs.mapatlases.client.screen.AtlasOverviewScreen) has not been correctly initialised, please send this crash log to the mod author. This is usually caused by calling setScreen on the wrong thread.
	at net.minecraft.class_437.ensureEventsAreInitialized(class_437.java:3816)
	at net.minecraft.class_437.fabric_getBeforeTickEvent(class_437.java:3829)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.beforeTick(ScreenEvents.java:148)
	at net.minecraft.class_310.handler$cbm000$fabric-screen-api-v1$beforeScreenTick(class_310.java:14571)
	at net.minecraft.class_310.method_1572(class_310.java:1875)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_310.method_1574(class_310.java:1875)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by MehVahdJukaar** [comment]
i need latest.log

**Comment by MehVahdJukaar** [comment]
also version?

**Comment by RokLinen** [comment]
I'm using version 1.20.1

I just attempted to replicate the crash for this mod once again by opening the book but, inexplicably, the atlas is no longer crashing when I open it. I guess it resolved itself somehow, at least for now.

Here's the log for when it happened:

[2024-03-01-6.log](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/14470085/2024-03-01-6.log)

**Comment by MehVahdJukaar** [comment]
please send the file instead of pasting all its content here. Also i dont think thats the one from before, I dont see that error, time doesnt match either

**Comment by RokLinen** [comment]
Ok just check my last comment. I've updated it to include the file.

**Comment by MehVahdJukaar** [comment]
im not sure what could cause this. try with just the mod installed. if it does not happen must be some other mod doing

**Comment by RokLinen** [comment]
Yeah I suppose so, I do use a lot of other mods, would be a long shot to figure that out but at least it seems to be working now.

Thank you for your time.

**Comment by RokLinen** [comment]
I just realized that the crash ONLY happens when I try to open the atlas using my ps4 controller (I use controlify mod). It doesn't crash when I just right click it with the mouse. Just thought I'd share this in the hopes it might shed light on the issue.
