### ISSUE TITLE
Fabric 1.20.1 Crash when Atlas is in Inventory

### ISSUE THREAD

**Issue by LocoPineapples** [MehVahdJukaar/mapatlases-neoforge#111]
When going into the creative menu and adding an atlas to your inventory, the game immediately crashes. The crash report is provided. There's 96 mods or so in this pack, so I'm not sure what exactly is causing an incompatibility.

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-03-19 15:51:54
Description: Unexpected error

java.lang.AssertionError: Cardinal Component for Map Atlases could not be gathered.This is a Cardinal Component bug! 
	at pepjebs.mapatlases.map_collection.fabric.IMapCollectionImpl.get(IMapCollectionImpl.java:43)
	at pepjebs.mapatlases.map_collection.IMapCollection.get(IMapCollection.java)
	at pepjebs.mapatlases.item.MapAtlasItem.getMaps(MapAtlasItem.java:209)
	at pepjebs.mapatlases.client.MapAtlasesClient.cachePlayerState(MapAtlasesClient.java:120)
	at pepjebs.mapatlases.fabric.MapAtlasesFabricClient.lambda$clientInit$0(MapAtlasesFabricClient.java:14)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$bok000$fabric-lifecycle-events-v1$onEndTick(class_310.java:9522)
	at net.minecraft.class_310.method_1574(class_310.java:1957)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:486)
	at dev.onyxstudios.cca.internal.base.GenericContainerBuilder.factoryNameSuffix(GenericContainerBuilder.java:70)
	at dev.onyxstudios.cca.api.v3.component.ComponentContainer$Factory$Builder.factoryNameSuffix(ComponentContainer.java:194)
	at dev.onyxstudios.cca.internal.item.StaticItemComponentPlugin.getFactoryClass(StaticItemComponentPlugin.java:82)
	at dev.onyxstudios.cca.internal.item.StaticItemComponentPlugin.createItemStackContainerFactory(StaticItemComponentPlugin.java:70)
	at net.minecraft.class_1792.cardinal_createComponents(class_1792.java:2054)
	at net.minecraft.class_1799.getComponentContainer(class_1799.java:4656)
	at dev.onyxstudios.cca.api.v3.component.ComponentKey.maybeGet(ComponentKey.java:111)
	at pepjebs.mapatlases.map_collection.fabric.IMapCollectionImpl.get(IMapCollectionImpl.java:35)
	... 13 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at pepjebs.mapatlases.map_collection.fabric.IMapCollectionImpl.get(IMapCollectionImpl.java:43)
	at pepjebs.mapatlases.map_collection.IMapCollection.get(IMapCollection.java)
	at pepjebs.mapatlases.item.MapAtlasItem.getMaps(MapAtlasItem.java:209)
	at pepjebs.mapatlases.client.MapAtlasesClient.cachePlayerState(MapAtlasesClient.java:120)
	at pepjebs.mapatlases.fabric.MapAtlasesFabricClient.lambda$clientInit$0(MapAtlasesFabricClient.java:14)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$bok000$fabric-lifecycle-events-v1$onEndTick(class_310.java:9522)

-- Affected level --
Details:
	All players: 1 total; [class_746['LocoPineapple'/221, l='ClientLevel', x=7.50, y=75.00, z=44.50]]
	Chunk stats: 894, 894
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,73,48), Section: (at 0,9,0 in 0,4,3; chunk contains blocks 0,-64,48 to 15,319,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 227 game time, 227 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, Fabrication, Fabrication Grayscale, Moonlight Mods Dynamic Assets, distinguishedpotions:potion_overrides

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1078054600 bytes (1028 MiB) / 2327838720 bytes (2220 MiB) up to 8556380160 bytes (8160 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2216
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5176
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37560.64
	Virtual memory used (MB): 17163.12
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 7.60
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8160m -Xms256m
	Fabric Mods: 
		adaptive-tooltips: Adaptive Tooltips 1.3.0
		alternate-current: Alternate Current 1.7.0
		ambientenvironment: Ambient Environment 11.0.0.1
		ambientsounds: AmbientSounds 5.3.9
		amendments: Amendments 1.20-1.1.10
			mixinsquared: MixinSquared 0.1.1
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.2.14
		attributefix: AttributeFix 21.0.4
		axesareweapons: Axes Are Weapons 1.7.3
		balm-fabric: Balm 7.2.2
		barteringstation: Bartering Station 8.0.0
		betteradvancements: Better Advancements 0.3.2.162
		betteranimationscollection: Better Animations Collection 8.0.0
		betterchunkloading: Better chunk loading mod 1.20.1-3.3
		betterfpsdist: Better FPS distance Mod 1.20.1-4.3
		bettermounthud: Better Mount HUD 1.2.2
		betterthirdperson: Better Third Person 1.9.0
		biomemakeover: Biome Makeover 1.20.1-1.11.4
			taniwha: Taniwha 1.20.0-5.4.4
		blur: Blur (Fabric) 3.1.0
			midnightlib: MidnightLib 1.4.1
			satin: Satin 1.13.0
		boatbreakfix: Boat Break Fix 1.0.2
		bookshelf: Bookshelf 20.1.9
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		chat_heads: Chat Heads 0.10.32
		chunksending: Chunksending Mod 1.20.1-2.8
		clickadv: Clickable Advancements Mod 1.20.1-3.7
		clientcrafting: clientcrafting Mod 1.20.1-1.8
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.3
		collective: Collective 7.40
		connectivity: Connectivity Mod 1.20.1-5.5
		controlling: Controlling For Fabric 12.0.2
		creativecore: CreativeCore 2.11.24
			net_minecraftforge_eventbus: eventbus 6.0.3
		cull-less-leaves: Cull Less Leaves 1.3.0
		cupboard: cupboard 1.20.1-2.6
		disable_custom_worlds_advice: Disable Custom Worlds Advice 4.1
		distinguishedpotions: Distinguished Potions 8.0.2
		dynamic_fps: Dynamic FPS 3.4.2
		dynview: Dynamic View Mod 1.20.1-3.2
		easyanvils: Easy Anvils 8.0.2
		easymagic: Easy Magic 8.0.1
		ecologics: Ecologics 2.2.0
		enchdesc: EnchantmentDescriptions 17.0.14
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		fabric-api: Fabric API 0.92.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+1802ada577
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.4+1802ada577
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabrication: Fabrication 3.4.11+1.20
			lib39-deferral: Lib39 (Deferral) 1.5.0-pre2.2+1.19.3
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		fallingleaves: Falling Leaves 1.15.4
		farsight: Farsight Mod 1.20.1-4.2
			org_jctools_jctools-core: jctools-core 4.0.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		framework: Framework 0.6.16
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			org_javassist_javassist: javassist 3.29.2-GA
			org_reflections_reflections: reflections 0.10.2
		galosphere: Galosphere 1.20.1-1.4.1
			mm: Manningham Mills 2.3
		globalpacks: Global Data- & Resourcepacks 1.16.1_fabric
		goblintraders: Goblin Traders 1.9.3
		gpumemleakfix: Gpu memory leak fix mod 1.20.1-1.8
		guardvillagers: GuardVillagers 2.0.9-1.20.1
		immediatelyfast: ImmediatelyFast 1.2.10+1.20.4
			net_lenni0451_reflect: Reflect 1.3.2
		indium: Indium 1.0.30+mc1.20.4
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
		lazydfu: LazyDFU 0.1.3
		leavemybarsalone: Leave My Bars Alone 8.0.0
		leavesbegone: Leaves Be Gone 8.0.0
		letmedespawn: Let Me Despawn 1.2.0
		limitedchunks: Limited Chunkloading Mod 1.20.1-4.0
		lootintegrations: Loot integration Mod 1.20.1-3.4
		map_atlases: Map Atlases 1.20-6.0.3
		minecraft: Minecraft 1.20.1
		mobplaques: Mob Plaques 8.0.1
		modernfix: ModernFix 5.14.0+mc1.20.1
		modmenu: Mod Menu 7.2.2
		moonlight: Moonlight 1.20-2.11.4
		mousetweaks: Mouse Tweaks 2.25
		necronomicon: Necronomicon 1.4.2
		netherportalfix: NetherPortalFix 13.0.1
		notenoughanimations: NotEnoughAnimations 1.7.1
		origins: Origins 1.10.0
			apoli: Apoli 2.9.0
				additionalentityattributes: Additional Entity Attributes 1.3.0+1.20.0
				calio: Calio 1.11.0
				playerabilitylib: Pal 1.8.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		overflowingbars: Overflowing Bars 8.0.0
		pehkui: Pehkui 3.7.12+1.14.4-1.20.4
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		presencefootsteps: Presence Footsteps 1.9.2
			kirin: Kirin UI 1.15.4+1.20
		puzzleslib: Puzzles Lib 8.1.17
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		recipeessentials: recipeessentials Mod 1.20.1-3.3
		regrowth: Regrowth 83.31.1
		roughlyenoughitems: Roughly Enough Items 12.0.684
			error_notifier: Error Notifier 1.0.9
		searchables: Searchables 1.0.2
		smoothchunk: Smooth chunk save Mod 1.20.1-3.6
		sodium: Sodium 0.5.8+mc1.20.1
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.3.1
		structureessentials: Structure Essentials Mod 1.20.1-3.3
		stylisheffects: Stylish Effects 8.0.2
		supplementaries: Supplementaries 1.20-2.8.6
		tradingpost: Trading Post 8.0.2
		true-darkness-fork: True Darkness Fork 1.0.2-1.20.x
		villagernames: Villager Names 7.3
		visuality: Visuality 0.7.1+1.20
		visualworkbench: Visual Workbench 8.0.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.2+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Launched Version: fabric-loader-0.15.7-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3080/PCIe/SSE2 GL version 3.2.0 NVIDIA 551.76, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	CPU: 16x AMD Ryzen 7 5800X 8-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['LocoPineapple'/221, l='ServerLevel[New World]', x=7.50, y=75.00, z=44.50]]
	Data Packs: vanilla, fabric, Moonlight Mods Dynamic Assets, Recipes (incompatible), Sub_Origins_T1 (incompatible), Sub_Origins_T2 (incompatible), Sub_Origins_T3 (incompatible), Supplementaries Generated Pack, We-Have-the-Meats-main (incompatible), origin_blocks (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Comment by MehVahdJukaar** [comment]
check if cardinal components is updated. if it is this is likely their issue, as the message says

**Comment by LocoPineapples** [comment]
The latest version of Cardinal Components is 5.2.2, which is what I was on when it crashed. I checked both it and Fabric's versions, they're both completely up to date. I can submit this to Cardinal Components as well, if it's on their end then

**Comment by JayceTtheAce** [comment]
> The latest version of Cardinal Components is 5.2.2, which is what I was on when it crashed. I checked both it and Fabric's versions, they're both completely up to date. I can submit this to Cardinal Components as well, if it's on their end then

did you ever figure this out? I'm having the same issue and this kind of map mod is integral to the whole experience, and there's no other up to date version of any mod like this

**Comment by MehVahdJukaar** [comment]
If that fails is an issue form cardinal components mod as it's not doing its hot apparently

**Comment by ManoBambu** [comment]
bruh same problem lost my world can't enter it cuz of cardinal component

**Comment by MehVahdJukaar** [comment]
this is not a map atlases issue. Update cardinal components.if it persistes report to that mod
