### ISSUE TITLE
Crash on startup - 1.20.1

### ISSUE THREAD

**Issue by sadeegibson** [MehVahdJukaar/mapatlases-neoforge#145]
Hello,

I'm getting this crash report with only this mod and it's dependents installed:

[23:15:28] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.11
[23:15:28] [main/INFO]: Loading 70 mods:
	- cardinal-components 6.1.1
	   |-- cardinal-components-base 6.1.1
	   |-- cardinal-components-block 6.1.1
	   |-- cardinal-components-chunk 6.1.1
	   |-- cardinal-components-entity 6.1.1
	   |-- cardinal-components-item 6.1.1
	   |-- cardinal-components-level 6.1.1
	   |-- cardinal-components-scoreboard 6.1.1
	   \-- cardinal-components-world 6.1.1
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- fabric-api 0.92.2+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.2+85287f9f77
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- java 17
	- map_atlases 1.20-6.0.7
	- minecraft 1.20.1
	- moonlight 1.20-2.12.10
[23:15:28] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/hicks/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[23:15:28] [main/INFO]: Compatibility level set to JAVA_16
[23:15:28] [main/INFO]: Compatibility level set to JAVA_17
[23:15:29] [main/WARN]: Reference map 'map_atlases-fabric-refmap.json' for map_atlases.mixins.json could not be read. If this is a development environment you can ignore this message
[23:15:29] [main/WARN]: Error loading class: net/minecraft/class_8608 (java.lang.ClassNotFoundException: net/minecraft/class_8608)
[23:15:29] [main/WARN]: @Mixin target net.minecraft.class_8608 was not found mixins.cardinal_components_block.json:common.MixinChunkDataSender from mod cardinal-components-block
[23:15:29] [main/WARN]: Error loading class: net/minecraft/class_8608 (java.lang.ClassNotFoundException: net/minecraft/class_8608)
[23:15:29] [main/WARN]: @Mixin target net.minecraft.class_8608 was not found mixins.cardinal_components_chunk.json:common.MixinChunkDataSender from mod cardinal-components-chunk
[23:15:29] [main/WARN]: Error loading class: net/minecraft/class_9267 (java.lang.ClassNotFoundException: net/minecraft/class_9267)
[23:15:29] [main/WARN]: @Mixin target net.minecraft.class_9267 was not found mixins.cardinal_components_item.json:common.MixinItemStackComponentizationFix from mod cardinal-components-item
[23:15:29] [main/WARN]: Error loading class: twilightforest/TFMagicMapData$TFMapDecoration (java.lang.ClassNotFoundException: twilightforest/TFMagicMapData$TFMapDecoration)
[23:15:29] [main/WARN]: Error loading class: net/minecraft/class_8710$class_9154 (java.lang.ClassNotFoundException: net/minecraft/class_8710$class_9154)
[23:15:29] [main/WARN]: Error loading class: net/minecraft/class_8710$class_9154 (java.lang.ClassNotFoundException: net/minecraft/class_8710$class_9154)
[23:15:29] [main/WARN]: Error loading class: net/minecraft/class_8710$class_9154 (java.lang.ClassNotFoundException: net/minecraft/class_8710$class_9154)
[23:15:29] [main/WARN]: Error loading class: net/minecraft/class_8710$class_9154 (java.lang.ClassNotFoundException: net/minecraft/class_8710$class_9154)
[23:15:29] [main/WARN]: Error loading class: net/minecraft/class_8710$class_9154 (java.lang.ClassNotFoundException: net/minecraft/class_8710$class_9154)
[23:15:29] [main/WARN]: Error loading class: net/minecraft/class_8710$class_9154 (java.lang.ClassNotFoundException: net/minecraft/class_8710$class_9154)
[23:15:29] [main/WARN]: Error loading class: net/minecraft/class_18$class_8645 (java.lang.ClassNotFoundException: net/minecraft/class_18$class_8645)
[23:15:29] [main/WARN]: Error loading class: net/minecraft/class_8710$class_9154 (java.lang.ClassNotFoundException: net/minecraft/class_8710$class_9154)
[23:15:30] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[23:15:30] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.UnsupportedClassVersionError: net/minecraft/class_4284 has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/class_4284 has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraft.class_155.method_43250(class_155.java:281) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:61) ~[fabric-loader-0.15.11-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 2 more

**Comment by MehVahdJukaar** [comment]
It says that it doesn't work since Minecraft itself requires an older version of java

**Comment by sadeegibson** [comment]
Yeah, I was suspecting a mismatched Java version was the issue, since it was running in compatibility mode with an earlier version but was saying it couldn't read the class files of that type. I tried changing the settings in the installation to run Java 21 and then tried 22 as well, no dice on either working. Any fix I might be able to make on my side? I haven't seen anyone else with this issue on 1.20.1, so I feel like it must be something I'm missing!

**Comment by MehVahdJukaar** [comment]
To be honest I'm not sure. Try curse forge launcher

**Comment by pernalin9** [comment]
This also happened to me, my version is also 1.20.1, I only installed OptiFine and map atlases.
[crash-2024-08-12_14.21.13-client.txt](https://github.com/user-attachments/files/16578079/crash-2024-08-12_14.21.13-client.txt)

**Comment by MehVahdJukaar** [comment]
And there's your problem. You installed optifine. Never install that. With or without mods

**Comment by pernalin9** [comment]
Thank you for pointing this out. You're right, everything works fine without Optifine. Would you consider adding Optifine to the Known Incompatibilities list? This could help other users facing similar problem.

> And there's your problem. You installed optifine. Never install that. With or without mods这就是你的问题。您已安装 optifine。永远不要安装它。带或不带模组

**Comment by MehVahdJukaar** [comment]
Optifine should never be used and is known to cause all sorts of issues with mods. If it works seemingly without issues then it's just a miracle
