### ISSUE TITLE
Renderer Crash When Loading MC

### ISSUE THREAD

**Issue by disky00** [MehVahdJukaar/mapatlases-neoforge#159]
I'm receiving an error when attempting to start Minecraft after installing the Map Atlases mod. I'm running roughly 530 mods, but I've never had this type of crash before.

Any analysis would be very helpful, this mod looks great!

**Version Info:**
==========================
Minecraft 1.20.1
Fabric 0.15.11
Map Atlases 6.0.9

**Error Log Info:**
==========================
Description: Unexpected error

java.lang.NoSuchFieldError: CONFIG
	at club.iananderson.seasonhud.client.minimaps.MapAtlases.onHudRender(MapAtlases.java:71)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at MC//net.minecraft.client.gui.hud.InGameHud.handler$ghi002$fabric-rendering-v1$render(InGameHud.java:12386)
	at MC//net.minecraft.client.gui.hud.InGameHud.render(InGameHud.java:370)
	at MC//net.minecraft.client.render.GameRenderer.render(GameRenderer.java:926)
	at MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1219)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at club.iananderson.seasonhud.client.minimaps.MapAtlases.onHudRender(MapAtlases.java:71)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at MC//net.minecraft.client.gui.hud.InGameHud.handler$ghi002$fabric-rendering-v1$render(InGameHud.java:12386)
	at MC//net.minecraft.client.gui.hud.InGameHud.render(InGameHud.java:370)
Mixins in Stacktrace: None found

**Comment by MehVahdJukaar** [comment]
crash from this mod.
![image](https://github.com/user-attachments/assets/150257fb-ad88-4b12-80fb-b07e75d7eacc)

**Comment by disky00** [comment]
Okay, thanks very much!
