### ISSUE TITLE
Render crash when clicking on map gui

### ISSUE THREAD

**Issue by CPSRYAN** [MehVahdJukaar/mapatlases-neoforge#163]
Love the mod, small issue is that I cannot edit the map at all, as clicking on the gui for it causes the client to crash
Clicking the tabs or trying to put down a pin causes a crash :(

### Version Info:

Minecraft 1.20.1
Fabric 0.16.9
Map Atlases 6.0.9
Surveyor Atlases 0.1.0
Surveyor-0.6.25

### Error Log Info:
Description: mouseClicked event handler

java.lang.UnsupportedOperationException
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
	at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.removeIf(ImmutableCollections.java:152)
	at knot//pepjebs.mapatlases.client.screen.AtlasOverviewScreen.modifyExpressionValue$hpc000$surveyor_atlases$removeSurveyors(AtlasOverviewScreen.java:808)
	at knot//pepjebs.mapatlases.client.screen.AtlasOverviewScreen.addDecorationWidgets(AtlasOverviewScreen.java:569)
	at knot//pepjebs.mapatlases.client.screen.AtlasOverviewScreen.recalculateDecorationWidgets(AtlasOverviewScreen.java:516)
	at knot//pepjebs.mapatlases.client.screen.AtlasOverviewScreen.selectDimension(AtlasOverviewScreen.java:508)
	at knot//pepjebs.mapatlases.client.screen.DimensionBookmarkButton.method_25348(DimensionBookmarkButton.java:64)
	at knot//net.minecraft.class_339.method_25402(class_339.java:189)
	at knot//net.minecraft.class_4069.method_25402(class_4069.java:38)
	at knot//pepjebs.mapatlases.client.screen.AtlasOverviewScreen.method_25402(AtlasOverviewScreen.java:411)
	at knot//net.minecraft.class_312.method_1611(class_312.java:98)
	at knot//net.minecraft.class_437.method_25412(class_437.java:409)
	at knot//net.minecraft.class_312.method_1601(class_312.java:98)
	at knot//net.minecraft.class_312.method_22686(class_312.java:169)
	at knot//net.minecraft.class_1255.execute(class_1255.java:102)
	at knot//net.minecraft.class_312.method_22684(class_312.java:169)
	at knot//org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
	at knot//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at knot//com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)
	at knot//net.minecraft.class_1041.method_15998(class_1041.java:288)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1241)
	at knot//net.minecraft.class_310.method_1514(class_310.java:802)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	
[crash-2024-11-12_11.17.42-client.txt](https://github.com/user-attachments/files/17715691/crash-2024-11-12_11.17.42-client.txt)

**Comment by MehVahdJukaar** [comment]
seems to be called by surveyor which has a mixin into map atlases code
