### ISSUE TITLE
1.20.1 - Crash on latest update - map_atlases-1.20-5.9.4-all.jar - FORGE

### ISSUE THREAD

**Issue by celsiusqc** [MehVahdJukaar/mapatlases-neoforge#48]
https://gist.github.com/celsiusqc/ca5e060f34ae79f7ad98124b03b94544

**Comment by MehVahdJukaar** [comment]
update moonlight

**Comment by TheaRTGGaming** [comment]
even after updating Moonlight still crashes

map_atlases-1.20-5.9.6-all.jar

moonlight-1.20-2.8.52-forge.jar

Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method renderMapAtlasItem(ZLnet/minecraft/world/item/ItemStack;)Z in map_atlases.mixins.json:ItemInHandRendererMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap map_atlases.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[mixin-0.8.5.jar%23100!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at com.llamalad7.mixinextras.sugar.impl.SugarWrapperInjectionInfo.doPostInject(SugarWrapperInjectionInfo.java:132) ~[MixinExtras-0.2.0.jar%23525!/:?] {re:classloading}
	at com.llamalad7.mixinextras.sugar.impl.SugarWrapperInjectionInfo.postInject(SugarWrapperInjectionInfo.java:126) ~[MixinExtras-0.2.0.jar%23525!/:?] {re:classloading}
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	... 31 more

**Comment by TheaRTGGaming** [comment]
The only working versions are as followed

map_atlases_forge-1.20-5.4.0.jar

moonlight-1.20-2.8.28-forge.jar

**Comment by MehVahdJukaar** [comment]
please always send latest.log
