### ISSUE TITLE
Crash while opening an atlas with supplementaries installed

### ISSUE THREAD

**Issue by Tlotro** [MehVahdJukaar/mapatlases-neoforge#74]
Minecraft crashes when opening an atlas in a region a map of which it generated itself.
This doesn't happen without supplementaries mod installed.

Minecraft version: 1.20.1
Forge version: 47.2.18
Mod version: 2.7.5

Crash log:

Description: Unexpected error

java.lang.NoSuchMethodError: 'pepjebs.mapatlases.capabilities.MapCollectionCap pepjebs.mapatlases.item.MapAtlasItem.getMaps(net.minecraft.world.item.ItemStack, net.minecraft.world.level.Level)'
	at net.mehvahdjukaar.moonlight.api.integration.forge.MapAtlasCompatImpl.getSavedDataFromAtlas(MapAtlasCompatImpl.java:29) ~[moonlight-1.20-2.8.70-forge.jar%23309!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.integration.MapAtlasCompat.getSavedDataFromAtlas(MapAtlasCompat.java) ~[moonlight-1.20-2.8.70-forge.jar%23309!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.map.MapHelper.getMapData(MapHelper.java:30) ~[moonlight-1.20-2.8.70-forge.jar%23309!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.map.MapHelper.toggleMarkersAtPos(MapHelper.java:120) ~[moonlight-1.20-2.8.70-forge.jar%23309!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.overrides.MapMarkerBehavior.tryPerformingAction(MapMarkerBehavior.java:33) ~[supplementaries-1.20-2.7.14.jar%23327!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.overrides.InteractEventOverrideHandler.onItemUsedOnBlock(InteractEventOverrideHandler.java:194) ~[supplementaries-1.20-2.7.14.jar%23327!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.ServerEvents.onRightClickBlock(ServerEvents.java:75) ~[supplementaries-1.20-2.7.14.jar%23327!/:?] {re:mixin,re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge.onUseBlock(ServerEventsForge.java:63) ~[supplementaries-1.20-2.7.14.jar%23327!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.forge.__ServerEventsForge_onUseBlock_RightClickBlock.invoke(.dynamic) ~[supplementaries-1.20-2.7.14.jar%23327!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:801) ~[forge-1.20.1-47.2.18-universal.jar%23347!/:?] {re:mixin,re:classloading,pl:mixin:APP:apotheosis.mixins.json:ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233746_(MultiPlayerGameMode.java:301) ~[client-1.20.1-20230612.114412-srg.jar%23342!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.cofhcore.json:MultiPlayerGameModeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233740_(MultiPlayerGameMode.java:291) ~[client-1.20.1-20230612.114412-srg.jar%23342!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.cofhcore.json:MultiPlayerGameModeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:250) ~[client-1.20.1-20230612.114412-srg.jar%23342!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.cofhcore.json:MultiPlayerGameModeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233732_(MultiPlayerGameMode.java:290) ~[client-1.20.1-20230612.114412-srg.jar%23342!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.cofhcore.json:MultiPlayerGameModeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1698) ~[client-1.20.1-20230612.114412-srg.jar%23342!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1976) ~[client-1.20.1-20230612.114412-srg.jar%23342!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1795) ~[client-1.20.1-20230612.114412-srg.jar%23342!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23342!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23342!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.18.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.18.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.18.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.18.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: 
	Supplementaries (supplementaries), Version: 1.20-2.7.14
		Issue tracker URL: https://github.com/MehVahdJukaar/Supplementaries/issues
		at TRANSFORMER/supplementaries@1.20-2.7.14/net.mehvahdjukaar.supplementaries.common.events.overrides.MapMarkerBehavior.tryPerformingAction(MapMarkerBehavior.java:33)

	Moonlight Library (moonlight), Version: 1.20-2.8.70
		Issue tracker URL: https://github.com/MehVahdJukaar/Moonlight/issues
		at TRANSFORMER/moonlight@1.20-2.8.70/net.mehvahdjukaar.moonlight.api.integration.forge.MapAtlasCompatImpl.getSavedDataFromAtlas(MapAtlasCompatImpl.java:29)
Stacktrace:
	at net.mehvahdjukaar.moonlight.api.integration.forge.MapAtlasCompatImpl.getSavedDataFromAtlas(MapAtlasCompatImpl.java:29) ~[moonlight-1.20-2.8.70-forge.jar%23309!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.integration.MapAtlasCompat.getSavedDataFromAtlas(MapAtlasCompat.java) ~[moonlight-1.20-2.8.70-forge.jar%23309!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.map.MapHelper.getMapData(MapHelper.java:30) ~[moonlight-1.20-2.8.70-forge.jar%23309!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.map.MapHelper.toggleMarkersAtPos(MapHelper.java:120) ~[moonlight-1.20-2.8.70-forge.jar%23309!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.overrides.MapMarkerBehavior.tryPerformingAction(MapMarkerBehavior.java:33) ~[supplementaries-1.20-2.7.14.jar%23327!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.overrides.InteractEventOverrideHandler.onItemUsedOnBlock(InteractEventOverrideHandler.java:194) ~[supplementaries-1.20-2.7.14.jar%23327!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.ServerEvents.onRightClickBlock(ServerEvents.java:75) ~[supplementaries-1.20-2.7.14.jar%23327!/:?] {re:mixin,re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge.onUseBlock(ServerEventsForge.java:63) ~[supplementaries-1.20-2.7.14.jar%23327!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.forge.__ServerEventsForge_onUseBlock_RightClickBlock.invoke(.dynamic) ~[supplementaries-1.20-2.7.14.jar%23327!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:801) ~[forge-1.20.1-47.2.18-universal.jar%23347!/:?] {re:mixin,re:classloading,pl:mixin:APP:apotheosis.mixins.json:ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233746_(MultiPlayerGameMode.java:301) ~[client-1.20.1-20230612.114412-srg.jar%23342!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.cofhcore.json:MultiPlayerGameModeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233740_(MultiPlayerGameMode.java:291) ~[client-1.20.1-20230612.114412-srg.jar%23342!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.cofhcore.json:MultiPlayerGameModeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:250) ~[client-1.20.1-20230612.114412-srg.jar%23342!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.cofhcore.json:MultiPlayerGameModeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233732_(MultiPlayerGameMode.java:290) ~[client-1.20.1-20230612.114412-srg.jar%23342!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.cofhcore.json:MultiPlayerGameModeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1698) ~[client-1.20.1-20230612.114412-srg.jar%23342!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1976) ~[client-1.20.1-20230612.114412-srg.jar%23342!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Tlotro'/195, l='ClientLevel', x=-184.58, y=71.00, z=-460.78]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (-160,78,-384), Section: (at 0,14,0 in -10,4,-24; chunk contains blocks -160,-64,-384 to -145,319,-369), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 12056 game time, 12056 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:455) ~[client-1.20.1-20230612.114412-srg.jar%23342!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries-common.mixins.json:ClientLevelMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23342!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23342!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.18.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.18.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.18.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.18.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources, Moonlight Mods Dynamic Assets

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Launched Version: forge-47.2.18
	Backend library: LWJGL version 3.3.1 build 7
	Window size: 1920x1057
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, Moonlight Mods Dynamic Assets
	Current Language: en_us
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Tlotro'/195, l='ServerLevel[New World]', x=-184.58, y=71.00, z=-460.78]]
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.18.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.18.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.18.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.18.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.18.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@4.9.0
		lowcodefml@null
	Crash Report UUID: b939b2a0-b8ce-47e4-9625-bbfcd1a4b69d
	FML: 47.2
	Forge: net.minecraftforge:47.2.18

**Comment by MehVahdJukaar** [comment]
Is this relevant when using the latest versions of the mods?

**Comment by Tlotro** [comment]
After updating supplementaries, the issue has been resolved.
