### ISSUE TITLE
Game crash when use right click with map in hands 1.20.1

### ISSUE THREAD

**Issue by Kogomre** [MehVahdJukaar/mapatlases-neoforge#78]
Hi i get crash and this error
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'pepjebs.mapatlases.map_collection.IMapCollection pepjebs.mapatlases.item.MapAtlasItem.getMaps(net.minecraft.world.item.ItemStack, net.minecraft.world.level.Level)'

map_atlases-1.20-5.12.7-all.jar
forge-47.2.19

**Comment by MehVahdJukaar** [comment]
check all your mods are updated. Then double check. Then send me the full latest.log

**Comment by Kogomre** [comment]
Update all mods for latest version, but this dont help.

Description: Unexpected error

java.lang.NoSuchMethodError: 'pepjebs.mapatlases.map_collection.IMapCollection pepjebs.mapatlases.item.MapAtlasItem.getMaps(net.minecraft.world.item.ItemStack, net.minecraft.world.level.Level)'
	at net.mehvahdjukaar.moonlight.api.integration.MapAtlasCompat.getSavedDataFromAtlas(MapAtlasCompat.java:27) ~[Moonlight-1.20-2.8.81-forge.jar%23421!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.map.MapHelper.getMapData(MapHelper.java:30) ~[Moonlight-1.20-2.8.81-forge.jar%23421!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.map.MapHelper.toggleMarkersAtPos(MapHelper.java:120) ~[Moonlight-1.20-2.8.81-forge.jar%23421!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.overrides.MapMarkerBehavior.tryPerformingAction(MapMarkerBehavior.java:33) ~[Supplementaries-1.20-2.7.22.jar%23460!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.overrides.InteractEventOverrideHandler.onItemUsedOnBlock(InteractEventOverrideHandler.java:196) ~[Supplementaries-1.20-2.7.22.jar%23460!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.ServerEvents.onRightClickBlock(ServerEvents.java:75) ~[Supplementaries-1.20-2.7.22.jar%23460!/:?] {re:mixin,re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge.onUseBlock(ServerEventsForge.java:63) ~[Supplementaries-1.20-2.7.22.jar%23460!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.forge.__ServerEventsForge_onUseBlock_RightClickBlock.invoke(.dynamic) ~[Supplementaries-1.20-2.7.22.jar%23460!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:801) ~[forge-1.20.1-47.2.19-universal.jar%23487!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233746_(MultiPlayerGameMode.java:301) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233740_(MultiPlayerGameMode.java:291) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:250) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233732_(MultiPlayerGameMode.java:290) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1698) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1976) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1795) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.19.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.19.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.19.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.19.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: 
	Supplementaries (supplementaries), Version: 1.20-2.7.22
		Issue tracker URL: https://github.com/MehVahdJukaar/Supplementaries/issues
		at TRANSFORMER/supplementaries@1.20-2.7.22/net.mehvahdjukaar.supplementaries.common.events.overrides.MapMarkerBehavior.tryPerformingAction(MapMarkerBehavior.java:33)

	Moonlight Library (moonlight), Version: 1.20-2.8.81
		Issue tracker URL: https://github.com/MehVahdJukaar/Moonlight/issues
		at TRANSFORMER/moonlight@1.20-2.8.81/net.mehvahdjukaar.moonlight.api.integration.MapAtlasCompat.getSavedDataFromAtlas(MapAtlasCompat.java:27)
Stacktrace:
	at net.mehvahdjukaar.moonlight.api.integration.MapAtlasCompat.getSavedDataFromAtlas(MapAtlasCompat.java:27) ~[Moonlight-1.20-2.8.81-forge.jar%23421!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.map.MapHelper.getMapData(MapHelper.java:30) ~[Moonlight-1.20-2.8.81-forge.jar%23421!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.map.MapHelper.toggleMarkersAtPos(MapHelper.java:120) ~[Moonlight-1.20-2.8.81-forge.jar%23421!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.overrides.MapMarkerBehavior.tryPerformingAction(MapMarkerBehavior.java:33) ~[Supplementaries-1.20-2.7.22.jar%23460!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.overrides.InteractEventOverrideHandler.onItemUsedOnBlock(InteractEventOverrideHandler.java:196) ~[Supplementaries-1.20-2.7.22.jar%23460!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.ServerEvents.onRightClickBlock(ServerEvents.java:75) ~[Supplementaries-1.20-2.7.22.jar%23460!/:?] {re:mixin,re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge.onUseBlock(ServerEventsForge.java:63) ~[Supplementaries-1.20-2.7.22.jar%23460!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.forge.__ServerEventsForge_onUseBlock_RightClickBlock.invoke(.dynamic) ~[Supplementaries-1.20-2.7.22.jar%23460!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:801) ~[forge-1.20.1-47.2.19-universal.jar%23487!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233746_(MultiPlayerGameMode.java:301) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233740_(MultiPlayerGameMode.java:291) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:250) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233732_(MultiPlayerGameMode.java:290) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1698) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1976) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Kogomre'/110, l='ClientLevel', x=-225.93, y=71.00, z=-534.37]]
	Chunk stats: 1024, 453
	Level dimension: minecraft:overworld
	Level spawn location: World: (-48,75,-16), Section: (at 0,11,0 in -3,4,-1; chunk contains blocks -48,-64,-16 to -33,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 262308 game time, 225211 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:455) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries-common.mixins.json:ClientLevelMixin,pl:mixin:APP:embeddium.mixins.json:core.world.biome.ClientWorldMixin,pl:mixin:APP:embeddium.mixins.json:core.world.map.ClientWorldMixin,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel,pl:mixin:APP:the_bumblezone-common.mixins.json:client.ClientLevelAccessor,pl:mixin:APP:the_bumblezone-common.mixins.json:client.ClientLevelMixin,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:embeddiumplus.mixin.json:dynlights.ClientLevelMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.19.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.19.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.19.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.19.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: the_bumblezone:add_pack/anti_tropophobia, the_bumblezone:add_pack/ancient_luminescent_contrast_increase, vanilla, mod_resources, Moonlight Mods Dynamic Assets, twilightdelight:shader_compatible_fiery, file/1.20+Create+Camera+1.2.1.zip, Steam 'n' Rails Green Signals, Steam 'n' Rails Legacy Semaphores, supplementaries:darker_ropes, file/SE Vanilla Consistency 1.20.1.zip, create_central_kitchen:create_styled, eatinganimations_compat

**Comment by MehVahdJukaar** [comment]
you sure you on latest map atlases?

**Comment by Kogomre** [comment]
What the diffirence? Why version early start with 5, but latest start with 2?
map_atlases-1.20-2.7.10.jar and map_atlases-1.20-5.12.7-all.jar?

**Comment by MehVahdJukaar** [comment]
Oh must have messed numbering up

**Comment by Kogomre** [comment]
thx for help, now its work!)
